name: Hi project workflow



on: 

  push:

    branches:

      - main

  pull_request:

    branches:

      - main

  workflow_dispatch:



jobs:

  hello:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Hi world

        run: echo "Hi world"

        shell: bash



  goodbye:

    runs-on: ubuntu-latest

    steps:

      - name: see you world

        run: echo "See you world"

        shell: bash
